---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoflow-ce-staging
  labels:
    app: autoflow-ce-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoflow-ce-staging
  template:
    metadata:
      labels:
        app: autoflow-ce-staging
    spec:
      containers:
        - name: autoflow-ce-staging
          image: 900278004921.dkr.ecr.ap-southeast-1.amazonaws.com/autoflow-ce-staging/autoflow-ce-staging:bf10b14c0df0afe2cb7a33870d8811376760cef0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: autoflow-ce-staging-config

---
apiVersion: v1
kind: Service
metadata:
  name: autoflow-ce-staging
  labels:
    app: autoflow-ce-staging
spec:
  type: NodePort  # Use LoadBalancer if you want public access
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: autoflow-ce-staging


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autoflow-ce-staging-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"   # Optional if using cert-manager
spec:
  tls:
    - hosts:
        - autoflow-ce-api-staging.botauto.online   # Replace with your actual domain
      secretName: autoflow-ce-staging-tls   # TLS certificate secret name
  rules:
    - host: autoflow-ce-api-staging.botauto.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autoflow-ce-staging
                port:
                  number: 3000




